const $=id=>document.getElementById(id);let start=null,end=null,teams=[],current=-1,mode='work',drag=false,dragValue=true,specialSelection=new Set();
const pad=n=>String(n).padStart(2,'0');const fmt=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;const parse=s=>{let [y,m,d]=s.split('-').map(Number);return new Date(y,m-1,d)};const addDays=(d,n)=>new Date(d.getFullYear(),d.getMonth(),d.getDate()+n);const inRange=d=>start&&end&&d>=start&&d<=end;
let now=new Date();$('startDate').value=fmt(now);$('endDate').value=fmt(addDays(now,6));
$('applyRange').onclick=()=>{let s=parse($('startDate').value),e=parse($('endDate').value);if(e<s)return alert('End date must be after start date.');start=s;end=e;render()};$('applyRange').click();
$('addTeam').onclick=()=>{let name=$('teamName').value.trim();if(!name)return alert('Enter a team name.');teams.push({name,defaultStart:$('defaultStart').value,defaultEnd:$('defaultEnd').value,work:new Set(),special:{}});current=teams.length-1;$('teamName').value='';renderTabs();render()};
function renderTabs(){$('teamTabs').innerHTML='';teams.forEach((t,i)=>{let b=document.createElement('button');b.textContent=t.name;b.className=i===current?'active':'';b.onclick=()=>{current=i;specialSelection.clear();renderTabs();render()};$('teamTabs').appendChild(b)})}
$('workMode').onclick=()=>setMode('work');$('specialMode').onclick=()=>setMode('special');function setMode(m){mode=m;specialSelection.clear();$('workMode').classList.toggle('active',m==='work');$('specialMode').classList.toggle('active',m==='special');$('specialEditor').classList.toggle('hidden',m!=='special');render()}
document.addEventListener('mouseup',()=>drag=false);
function monthsInRange(){let a=[],d=new Date(start.getFullYear(),start.getMonth(),1),last=new Date(end.getFullYear(),end.getMonth(),1);while(d<=last){a.push(new Date(d));d=new Date(d.getFullYear(),d.getMonth()+1,1)}return a}
function render(){let box=$('months');box.innerHTML='';if(current<0){box.innerHTML='<p>Add a team to begin.</p>';return}monthsInRange().forEach(m=>box.appendChild(monthCard(m)));status()}
function monthCard(m){let t=teams[current],card=document.createElement('div');card.className='month';let h=document.createElement('h3');h.textContent=m.toLocaleString('en-US',{month:'long',year:'numeric'});card.appendChild(h);let week=document.createElement('div');week.className='week';['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].forEach(x=>{let d=document.createElement('div');d.textContent=x;week.appendChild(d)});card.appendChild(week);let grid=document.createElement('div');grid.className='grid';let first=new Date(m.getFullYear(),m.getMonth(),1),off=(first.getDay()+6)%7,days=new Date(m.getFullYear(),m.getMonth()+1,0).getDate();for(let i=0;i<off;i++){let e=document.createElement('div');grid.appendChild(e)}for(let n=1;n<=days;n++){let d=new Date(m.getFullYear(),m.getMonth(),n),ds=fmt(d),cell=document.createElement('div');cell.className='day';if(!inRange(d))cell.classList.add('disabled');else if(t.special[ds])cell.classList.add('specialDay');else if(t.work.has(ds))cell.classList.add('work');if(specialSelection.has(ds))cell.classList.add('selected');cell.innerHTML=`<div class='num'>${n}</div><div class='shift'>${!inRange(d)?'Outside range':t.special[ds]?`${t.special[ds].start} – ${t.special[ds].end}`:t.work.has(ds)?`${t.defaultStart} – ${t.defaultEnd}`:'REST DAY'}</div>`;if(inRange(d)){cell.onmousedown=e=>{e.preventDefault();drag=true;if(mode==='work'){dragValue=!t.work.has(ds);setWork(ds,dragValue)}else{t.work.add(ds);specialSelection.has(ds)?specialSelection.delete(ds):specialSelection.add(ds)}render()};cell.onmouseenter=()=>{if(!drag)return;if(mode==='work')setWork(ds,dragValue);else{t.work.add(ds);specialSelection.add(ds)}render()}}grid.appendChild(cell)}card.appendChild(grid);return card}
function setWork(ds,v){let t=teams[current];if(v)t.work.add(ds);else{t.work.delete(ds);delete t.special[ds]}}
$('applySpecial').onclick=()=>{if(!specialSelection.size)return alert('Select special dates first.');let t=teams[current];specialSelection.forEach(ds=>{t.work.add(ds);t.special[ds]={start:$('specialStart').value,end:$('specialEnd').value}});specialSelection.clear();render()};$('removeSpecial').onclick=()=>{let t=teams[current];specialSelection.forEach(ds=>delete t.special[ds]);specialSelection.clear();render()};
function eachDate(fn){for(let d=new Date(start);d<=end;d=addDays(d,1))fn(new Date(d))}$('allBtn').onclick=()=>{if(current<0)return;eachDate(d=>teams[current].work.add(fmt(d)));render()};$('weekdaysBtn').onclick=()=>{if(current<0)return;eachDate(d=>{if(d.getDay()>=1&&d.getDay()<=5)teams[current].work.add(fmt(d))});render()};$('clearBtn').onclick=()=>{if(current<0)return;teams[current].work.clear();teams[current].special={};render()};
function status(){let t=teams[current],total=0,w=0;eachDate(d=>{total++;if(t.work.has(fmt(d)))w++});$('status').innerHTML=`<b>${t.name}</b> — Working days: ${w} | Rest days: ${total-w} | Special shifts: ${Object.keys(t.special).length}`}
function timeNum(s){let [h,m]=s.split(':').map(Number);return h+m/60}function timeLabel(v){v=((v%24)+24)%24;let h=Math.floor(v),m=Math.round((v-h)*60),p=h<12?'AM':'PM',dh=h%12||12;return m?`${dh}:${pad(m)} ${p}`:`${dh} ${p}`}
$('generate').onclick=generate;
function generate(){if(!teams.length)return alert('Add a team first.');let dates=[];eachDate(d=>dates.push(fmt(d)));let rowH=34,gap=58,left=115,right=30,top=80,width=1200,plotW=width-left-right,totalRows=dates.length*teams.length+(teams.length-1)*2,height=top+totalRows*rowH+80,svg=$('timeline');svg.setAttribute('viewBox',`0 0 ${width} ${height}`);svg.setAttribute('height',height);svg.innerHTML='';const el=(tag,a={},text='')=>{let x=document.createElementNS('http://www.w3.org/2000/svg',tag);Object.entries(a).forEach(([k,v])=>x.setAttribute(k,v));if(text)x.textContent=text;svg.appendChild(x);return x};el('text',{x:width/2,y:25,'text-anchor':'middle','font-size':20,'font-weight':'bold'},'TEAM SHIFT TIMELINE');for(let h=0;h<=24;h+=3){let x=left+plotW*h/24;el('line',{x1:x,y1:top-20,x2:x,y2:height-45,stroke:'#999','stroke-dasharray':'3 5','stroke-width':.7});el('text',{x,y:top-30,'text-anchor':'middle','font-size':11},timeLabel(h))}let palette=['#1f77b4','#ff7f0e','#2ca02c','#d62728','#9467bd','#8c564b','#e377c2','#7f7f7f','#bcbd22','#17becf'];let y=top;teams.forEach((t,ti)=>{el('text',{x:8,y:y-18,'font-size':15,'font-weight':'bold'},t.name.toUpperCase());let ypos={};dates.forEach(ds=>{ypos[ds]=y;el('text',{x:left-10,y:y+5,'text-anchor':'end','font-size':10},new Date(ds+'T00:00:00').toLocaleDateString('en-US',{month:'short',day:'numeric'}));el('line',{x1:left,y1:y,x2:left+plotW,y2:y,stroke:'#bbb','stroke-width':.6});if(!t.work.has(ds)){el('rect',{x:left,y:y-10,width:plotW,height:20,fill:'#ddd',opacity:.45});el('text',{x:left+plotW/2,y:y+4,'text-anchor':'middle','font-size':10,'font-weight':'bold'},'REST DAY')}y+=rowH});let shifts=[...t.work].filter(ds=>dates.includes(ds)).sort();shifts.forEach((ds,si)=>{let sh=t.special[ds]||{start:t.defaultStart,end:t.defaultEnd},s=timeNum(sh.start),e=timeNum(sh.end);if(e<=s)e+=24;let color=palette[(si+ti*4)%palette.length],yy=ypos[ds];if(e<=24){let x=left+plotW*s/24,w=plotW*(e-s)/24;el('rect',{x,y:yy-10,width:w,height:20,fill:color,rx:2});el('text',{x:x+w/2,y:yy+4,'text-anchor':'middle','font-size':9,'font-weight':'bold'},`${timeLabel(s)} – ${timeLabel(e)}`)}else{let x=left+plotW*s/24,w=plotW*(24-s)/24;el('rect',{x,y:yy-10,width:w,height:20,fill:color,rx:2});el('text',{x:x-4,y:yy+4,'text-anchor':'end','font-size':9,'font-weight':'bold'},timeLabel(s));let nd=fmt(addDays(parse(ds),1));if(ypos[nd]!=null){let ne=e-24,w2=plotW*ne/24;el('rect',{x:left,y:ypos[nd]-10,width:w2,height:20,fill:color,rx:2});el('text',{x:left+w2+4,y:ypos[nd]+4,'font-size':9,'font-weight':'bold'},timeLabel(e))}}});y+=gap});}
$('downloadSvg').onclick=()=>{generate();let data=new XMLSerializer().serializeToString($('timeline')),blob=new Blob([data],{type:'image/svg+xml'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='team-shift-timeline.svg';a.click();URL.revokeObjectURL(a.href)};$('downloadJson').onclick=()=>{let data={startDate:fmt(start),endDate:fmt(end),teams:teams.map(t=>({name:t.name,defaultStart:t.defaultStart,defaultEnd:t.defaultEnd,workingDates:[...t.work],specialShifts:t.special}))},blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='shift-schedule.json';a.click();URL.revokeObjectURL(a.href)};
